[package]
name = "dsa-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
slh-dsa = "0.1.0"
signature = "=2.3.0-pre.4"
rand = "=0.8.5"

[[bench]]
name = "slhdsa_bench"
harness = false
