[package]
name = "dsa-bench"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.5"
ecdsa = "0.16.9"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] } 
p256 = "0.13.2"
rand = "0.8.0"
rand_core = "0.6.4"

[[bench]]
name = "ecdsa_bench"
harness = false


[[bench]]
name = "ed25519_bench"
harness = false
